### ISSUE TITLE
no file api.php console.php and web.php under routes folder

### ISSUE THREAD

**Issue by srikilam** [creativetimofficial/vue-material-dashboard-laravel#1]
no file api.php console.php and web.php under routes folder
step 
1. run composer update
2. error:
routes/web.php): failed to open stream: No such file or directory
routes/console.php): failed to open stream: No such file or directory
routes/api.php): failed to open stream: No such file or directory

**Comment by ivanfwc** [comment]
same problem, but i saw many folder missing.
After i ran the composer update first time, it gave me this error.
'vue-material-dashboard-laravel-master\laravel-json-api\bootstrap\cache directory must be present and writable.'

**Comment by srikilam** [comment]
After i ran the composer update
1. create folder cache under bootstrap folder.
2. create routes folder under root directory and create file (api.php, channel.php,console.php, web.php) under.
3. create folder framework under storage folder and create folder (cache, sessions, views) under this.
try again to run  composer update no error.

**Comment by teamupdivision** [comment]
Hello guys, sorry for the late reply.
We've updated the codebase to fix the issues you encountered, please check it out and let me know if you find anything else.

Thank you for using our products!
