### ISSUE TITLE
Laragon

### ISSUE THREAD

**Issue by cococococococo** [creativetimofficial/vue-material-dashboard-laravel#10]
Assuming I use Largon
I understand that to make this work I must not use "php artisan serve" command. When I use PHP ARTISAN SERVE I get the ip:port clearly indicated which I copy and use in .env config file on the frontend Vue side. 
In this case I don't get any IP, what do I enter then for variable  vor VUE_APP_API_BASE_URL ?
Currently mine are this one follow:
VUE_APP_APP_BASE_URL=http://192.168.1.20:8080/
VUE_APP_API_BASE_URL=http://localhost/laravel-json-api/public/api/v1

When I try to login I get a "Invalid credentials!" but when I look into the Laragon database table I see the admin and secret passowrd properly created into table and when I try to register I get a "Oops something went wrong"

**Comment by teamupdivision** [comment]
Hi @cococococococo 
Thanks for using our products.

Can you please make sure you have installed Laragon? 
The VUE_APP_API_BASE_URL should look like this if you would have installed it: http://laravel-json-api.test/api/v1

Please follow up after you installed Laragon for the JSON API
Thank you

**Comment by teamupdivision** [comment]
If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
