### ISSUE TITLE
cannot login to free material dashboard, network error. want to see free version work before purchasing 

### ISSUE THREAD

**Issue by kmuscwood** [creativetimofficial/vue-material-dashboard-laravel#11]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [ x] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

able to log into the frontend, with user and password displayed on the login screen

# Current Behavior

I can enter the user and password, and I verified that user is in the users table. when I hit "Lets Go" I get a network error.

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. followed the install instructions listed in the vue-material-dashboard README file.
2. did an 'npm run dev' to start up the dashboard
3. entered in the user and password specified on the login page.
4. get an Invalid Credentials popup, and when I Inpect the console I see the error listed above.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:macbook pro
* Operating System:BigSur 11.2.2
* Browser and Version:Chrome 88.0.4324.192 (x86_64)

## Failure Logs
at first I got a data undefined error, trying to read response.data when an exception occurs. 

when I got the data undefined error, I added a check to Login.vue to check that response and response.data is defined before accessing the data component, and I log the exception to the console, ---it is a network error.
e: Error: Network Error
at createError (createError.js?2d83:16)
at XMLHttpRequest.handleError (xhr.js?b50d:83)
xhr.js?b50d:178 POST http://localhost:3000/api/v1/login net::ERR_CONNECTION_REFUSED

got these errors before I tried to login:
GET https://static.hotjar.com/c/hotjar-99526.js?sv=7 net::ERR_NAME_NOT_RESOLVED

VM2835 analytics.js:38 POST https://stats.g.doubleclick.net/j/collect?t=dc&aip=1&_r=3&v=1&_v=j88&tid=UA-46172202-1&cid=1170637701.1614098154&jid=581385674&gjid=2097573773&_gid=344549045.1614786264&_u=SACAAEAAQAAAAC~&z=184435371 net::ERR_NAME_NOT_RESOLVED

VM2835 analytics.js:38 POST https://stats.g.doubleclick.net/j/collect?t=dc&aip=1&_r=3&v=1&_v=j88&tid=UA-46172202-22&cid=1170637701.1614098154&jid=859596022&gjid=376057807&_gid=344549045.1614786264&_u=SACAAEABQAAAAC~&z=765413393 net::ERR_NAME_NOT_RESOLVED

**Comment by kmuscwood** [comment]
Was able to get past the connection refused error by bringing up the laravel server.
**This should be put in the vue README file.**
I brought up laravel in 2 different ways: php artisan serve  --port 3000 and php -S localhost:3000 -t public/
The vue .env file contains: (I tried both 127.0.0.1 and localhost for the api base url)
UE_APP_APP_BASE_URL=http://localhost:8080/
VUE_APP_API_BASE_URL=http://127.0.0.1:3000/api/v1/

**However the login stays in pending.**

Saw reference in an older post about MAMP. Downloaded it, and brought it up.
do these steps:
Preferences
Document root:    select Choose
find your laravel project, and select public, and hit ok
Hit start to start the server.
***dont bring up laravel with artisan***

modify your vue .env file to have this: (8888 is the port MAMP is using)
VUE_APP_APP_BASE_URL=http://localhost:8080/
VUE_APP_API_BASE_URL=http://localhost:8888/api/v1/

bring it up: npm run dev

I can now login and get to the dashboard screen!

There are a few errors in the console, but will worry about those if they stop us from doing what we need to do.

[Vue warn]: Property or method "upgradeUrl" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <DashboardLayout> at src/pages/Dashboard/Layout/DashboardLayout.vue
       <App> at src/App.vue
         <Root>
...
vue-material.js?43f9:14420 Uncaught TypeError: Cannot read property 'parentNode' of null
    at eval (vue-material.js?43f9:14420)
...
xhr.js?b50d:178 GET http://localhost:8888/api/v1//me 404 (Not Found)
...

vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in created hook (Promise/async): "Error: Request failed with status code 404"

found in
...
---> <UserMenu> at src/pages/Dashboard/Layout/Extra/UserMenu.vue
       <Sidebar> at src/components/SidebarPlugin/SideBar.vue
         <DashboardLayout> at src/pages/Dashboard/Layout/DashboardLayout.vue
           <App> at src/App.vue
             <Root>
...
vue.runtime.esm.js?2b0e:1888 Error: Request failed with status code 404
    at createError (createError.js?2d83:16)
    at settle (settle.js?467f:17)
    at XMLHttpRequest.handleLoad (xhr.js?b50d:61)

**Comment by kmuscwood** [comment]
closing for now since i found a solution by reading tons of earlier posts.
one of these ways of bringing up laravel should be in the instructions!

**Comment by campi11** [comment]
> closing for now since i found a solution by reading tons of earlier posts. one of these ways of bringing up laravel should be in the instructions!

What is the solution?  i have same problem...
