### ISSUE TITLE
npm run dev error 

### ISSUE THREAD

**Issue by php143** [creativetimofficial/vue-material-dashboard-laravel#12]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

npm run dev not working

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

 ```
ERROR  Failed to compile with 1 error                                                                                              5:52:38 AM

 error  in ./src/main.js

Syntax Error: Error: [BABEL] /var/www/html/laramd/vue-material-dashboard/src/main.js: @babel/preset-env: The plugins/built-ins 'es.array.iterator, es.promise, es.object.assign, es.promise.finally' passed to the 'exclude' option are not
    valid. Please check data/[plugin-features|built-in-features].js in babel-preset-env (While processing: "/var/www/html/laramd/vue-material-dashboard/node_modules/@vue/babel-preset-app/index.js.overrides[0]$0")
    at Generator.next (<anonymous>)
    at Generator.next (<anonymous>)
    at Generator.next (<anonymous>)


 @ multi (webpack)-dev-server/client?http://172.16.200.96:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Desktop 
* Operating System: ubuntu 18.04.5 LTS
* Browser and Version: chrome 89.0.4389.90

**Comment by teamupdivision** [comment]
Hi @php143,

Thanks for reporting this issue and for using Creative Tim products.

Could you please try with these steps below:

npm install --save-dev @babel/core @babel/cli @babel/preset-env
npm install --save @babel/polyfill

Please let us know if this worked.

All the best,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi there @php143, 

We would like to check if the issue was solved and if there is anything else we can help with. 
Please let us know if you have any other issues. 

Best,
Updivision Team

**Comment by teamupdivision** [comment]
Hi @php143,

Hope this solved the problem. We will go ahead and close this ticket. If there is anything else that can be fixed or we can help with, please let us know.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
