### ISSUE TITLE
api.php is error not inclode php class

### ISSUE THREAD

**Issue by srikilam** [creativetimofficial/vue-material-dashboard-laravel#2]
api.php under route folder not include class
use Illuminate\Support\Facades\Route;
use CloudCreativity\LaravelJsonApi\Facades\JsonApi;

**Comment by teamupdivision** [comment]
Hello and thanks for using our products.

Those files are not needed, but nevertheless we included them in the latest version of code we just pushed.
Let us know if this fixed the problem.

Thank you
