### ISSUE TITLE
Please provide sample step 10,11 of Laravel API Project

### ISSUE THREAD

**Issue by srikilam** [creativetimofficial/vue-material-dashboard-laravel#3]
I cannot login to Laravel API it error 400 (bad request)
please add detail for step 10,11
10.Add the "Laravel Password Grant Client" id to your .env file under the CLIENT_ID key
11.Add the "Laravel Password Grant Client" secret to your .env file under the CLIENT_SECRET key

**Comment by kevinwaxi** [comment]
i also have a hard time configuring this part please help

**Comment by kevinwaxi** [comment]
just this morning found something that would help. Though its not exactly what you might expect but worked for me. try this code
https://argon-dashboard-laravel.creative-tim.com/docs/getting-started/quick-start.html#html5-doctype

**Comment by teamupdivision** [comment]
Hello and thanks for using our products.
We updated the installation instructions from the readme and pushed the latest version of code:
`Open the projects database and run the following query SELECT id, secret FROM laravel_json_api_pro.oauth_clients WHERE password_client = 1;
Add the id from step 10.) to your .env file under the CLIENT_ID key
Add the secret from step 10.) to your .env file under the CLIENT_SECRET key`

Let us know if this fixed the problem.

Thank you
