### ISSUE TITLE
api/v1/me is unauthorized on fresh install

### ISSUE THREAD

**Issue by orcu** [creativetimofficial/vue-material-dashboard-laravel#6]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Fresh install should be working. It is currently not functional.

# Current Behavior

Fresh install gives multiple errors (api and possibly related js errors).

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. fresh install using the installation guide (backend on Apache)
2. login on the app
3. see js errors on console at dashboard page such as:
[Vue warn]: Property or method "upgradeUrl" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <DashboardLayout> at src/pages/Dashboard/Layout/DashboardLayout.vue
       <App> at src/App.vue
         <Root>
4. One major error is that while it possible to log in, the json api does not work on retrieving user due to laravel auth api protection. Go to user profile page on the app and see that it is blank. See js error: 
GET http://localhost/laravel-json-api/public/index.php/api/v1/me [HTTP/1.1 401 Unauthorized 43ms]

## Also
1) Serving backend on artisan for development purposes hangs on login and does not work at all per this: https://stackoverflow.com/a/59098635. This is a huge time waste and should be explicitly included in the installing guide.
2) Laravel version is way outdated and cannot be upgraded due dependencies. This also affects laravel passport version, which is related with the reported bug.

**Comment by teamupdivision** [comment]
Hello, thanks for using Creative Tim products!

It seems your apache setup is incorrectly, index.php should not be present or required in when calling api endpoint.
Also, please make sure you assign a port for your server and make sure you use that port in the spa .env
We recommend using Laragon as a substitute for your current environment.

Let me know if we can help you further.
All the best

**Comment by orcu** [comment]
Hi. Changing Apache setup indeed worked, thanks! I got rid of the problem (in step # 4) by modifying virtual hosts to have designated local ServerNames and using the standard pretty urls of Laravel. (I still see a lot of js errors ( step # 3 ) on standard usage of the web site, but they seem minor.)
I would still suggest an explicit note in the installation guide on not using `php artisan serve` for serving the api. Thanks a lot!

**Comment by teamupdivision** [comment]
Hello, thank you very much.
Yes, we will address the artisan issue soon.

All the best
