### ISSUE TITLE
 Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `users` add unique `users_email_unique`(`email`))

### ISSUE THREAD

**Issue by cococococococo** [creativetimofficial/vue-material-dashboard-laravel#7]
when trying to migrate i get this error: 

 Illuminate\Database\QueryException  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `users` add unique `users_email_unique`(`email`))

I try to correct using  this: https://laravel-news.com/laravel-5-4-key-too-long-error

but in the public function boot there is already this line LaravelJsonApi::defaultApi('v1'); so I don't know well how to handle this. 
Schema::defaultStringLength(191);

If I keep both then I get this error:  Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'App\Providers\Schema' not found

**Comment by cococococococo** [comment]
solved using this thread ... https://laracasts.com/discuss/channels/laravel/php-artisan-migrate-errorclass-appprovidersschema-not-found?page=1

**Comment by teamupdivision** [comment]
Hello @cococococococo, thanks for using our products!
Glad you solved your issue quickly, are using by any chance MariaDB on your dev environment?

Thanks
